# Generated by Django 3.2 on 2022-12-20 18:46

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.UnicodeUsernameValidator()], verbose_name='Имя пользователя'),
        ),
    ]
